version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=*
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    volumes:
      - ./front:/app
      - /app/node_modules  # Usamos un volumen anónimo para node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000  # Variable de entorno para la API
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rufus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password

volumes:
  postgres_data:
